# Generated by Django 5.0.1 on 2024-01-31 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_analyzer', '0003_remove_resume_id_resume_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='uuid',
        ),
        migrations.AddField(
            model_name='resume',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
