# Generated by Django 5.0.1 on 2024-01-31 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_analyzer', '0004_remove_resume_uuid_resume_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='uuid',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
