# Generated by Django 5.0.1 on 2024-01-31 00:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_analyzer', '0005_resume_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='experiences',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
